//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    [PetaPoco.TableName("ChapterView")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class ChapterView
    {
        public byte Id { get; set; }
        public string Name { get; set; }
        public short TotalAyahs { get; set; }
        public string RevelationPlace { get; set; }
        public string Translator { get; set; }
        public string Language { get; set; }

        [PetaPoco.ResultColumn]
        public IList<VerseLite> Verses { get; set; }
    }

    public partial class VerseLite
    {
        public short VerseId { get; set; }
        public string Text { get; set; }
    }
}
