//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("City")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class City
    {
        public short Id { get; set; }
        public byte CountryId { get; set; }
        public byte StateId { get; set; }
        public Nullable<short> DisttId { get; set; }
        public string Name { get; set; }
        public string Abbr { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        [PetaPoco.Ignore]
        public virtual Country Country { get; set; }
        [PetaPoco.Ignore]
        public virtual District District { get; set; }
        [PetaPoco.Ignore]
        public virtual State State { get; set; }
    }
}
