//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("Contact")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class Contact
    {
        public System.Guid Id { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public Nullable<long> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CPhone { get; set; }
        public string HPhone { get; set; }
        public string WPhone { get; set; }
    }
}
