//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("CRUD")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class CRUD
    {
        public int Id { get; set; }
        public short OpType { get; set; }
        public string UserId { get; set; }
        public Nullable<int> RecId { get; set; }
        public byte[] OpTime { get; set; }
        public string Remarks { get; set; }
    }
}
