//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("District")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class District
    {
        public District()
        {
            this.Cities = new HashSet<City>();
        }
    
        public short Id { get; set; }
        public Nullable<byte> CountryId { get; set; }
        public Nullable<byte> StateId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }

        [PetaPoco.Ignore]
        public virtual ICollection<City> Cities { get; set; }
        [PetaPoco.Ignore]
        public virtual Country Country { get; set; }
        [PetaPoco.Ignore]
        public virtual State State { get; set; }
    }
}
