//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("Language")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class Language
    {
        public Language()
        {
            this.Books = new HashSet<Book>();
            this.LSChapters = new HashSet<LSChapter>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string ISO1Code { get; set; }
        public string ISO2Code { get; set; }
        public string URL { get; set; }
    
        [PetaPoco.Ignore]
        public virtual ICollection<Book> Books { get; set; }
        [PetaPoco.Ignore]
        public virtual ICollection<LSChapter> LSChapters { get; set; }
    }
}
