//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("LSChapter")]
    [PetaPoco.PrimaryKey("Id,TransId", autoIncrement = false)]
    public partial class LSChapter
    {
        public byte Id { get; set; }
        public int TransId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
