//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("Role")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class Role
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] LastChanged { get; set; }
    }
}
