//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("User")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class User
    {
        public string Id { get; set; }
        public string First { get; set; }
        public string Middle { get; set; }
        public string Last { get; set; }
        public string email { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public int Role { get; set; }
    }
}
