//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quran.Model
{
    using System;
    using System.Collections.Generic;

    [PetaPoco.TableName("VersesView")]
    [PetaPoco.PrimaryKey("Id")]
    public partial class VerseView
    {
        public short Id { get; set; }
        public byte Chapter { get; set; }
        public string Text { get; set; }
        public string ISO1Code { get; set; }
        public string Description { get; set; }
        public int TransId { get; set; }
        public byte ScriptId { get; set; }
    }
}
